---

- name: Add the key
  apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893

- name: install .NET Core SDK
  apt: name=dotnet-dev-1.0.0-preview2-003131 update_cache=yes

- name: install nodejs
  apt: name=nodejs state=present

- name: install npm
  apt: name=npm state=present

- name: install sdk for node
  npm: name=azure global=yes state=present

