---
- name: Application Server Installation Packages
  hosts: appserver
  remote_user: Navigator
  sudo: yes

  vars:
    - update_apt_cache: yes

  vars_files:
    - env_vars/production

  roles:
    - common
    - nodejs
    - core

