---

- name: Install list of npm packages
  npm: name={{item}} global=yes
  with_items:
       - npm3
       - bower 
       - grunt-cli

- name: Install Azure SDK for node
  npm: name=azure global=yes state=present












