---


- name: Add the key
  apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893

- name: install nodejs
  apt: name=nodejs state=present

- name: install npm
  apt: name=npm state=present

- name: Install list of npm packages
  npm: name={{item}} global=yes
  with_items:
       - gulp
       - gulp-cli
       - typings
       - typescript
       - ts-node

- name: Install list of yoman packages
  npm: name={{item}} global=yes
  with_items:
       - yoman
       - generator-aspnet







