---

- name: Add the key
  apt_key: keyserver=apt-mo.trafficmanager.net id=417A0893

- name: install nodejs
  apt: name=nodejs state=present

- name: install npm
  apt: name=npm state=present

- name: install gulp
- npm: name=gulp global=yes
