---
galaxy_info:
  author: tumf
  description: Install Docker Compose
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
dependencies: []
