---
- name: update the system and install apt-transport-https and ca-certificates
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add the gpg key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add the docker.list file
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: install docker-engine
  apt: name=docker-engine update_cache=yes

- name: add a docker group
  group: name=docker state=present

- name: add the user to the group docker
  user: name={{ ansible_ssh_user }} group=docker

- name: start docker engine
  service: name=docker state=running enabled=true

- name: Install docker-py
  package:
    name: python-docker
    state: present

- name: download git prompt script
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: /home/{{ ansible_ssh_user }}/.git-prompt.sh

- name: add the file source to bashrc
  blockinfile:
    dest: /home/{{ ansible_ssh_user }}/.bashrc
    block: |
     source ~/.git-prompt.sh
     PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

- name: download the binary file
  get_url:
    url: https://github.com/Azure/azurefile-dockervolumedriver/releases/download/v0.5.1/azurefile-dockervolumedriver
    dest: /usr/bin/
    mode: 0555

- name: copy the azurefile-dockervolumedriver file
  template: src=azurefile-dockervolumedriver.j2 dest=/etc/default/azurefile-dockervolumedriver

- name: copy the azazurefile-dockervolumedriver.service file
  template: src=azurefile-dockervolumedriver.service.j2 dest=/etc/systemd/system/azurefile-dockervolumedriver.service

- name: start the docker volume driver
  service: name=azurefile-dockervolumedriver state=started enabled=yes
