---
- name: update the system and install apt-transport-https and ca-certificates
  apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add the gpg key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: add the docker.list file
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: install docker-engine
  apt: name=docker-engine update_cache=yes

- name: add a docker group
  group: name=docker state=present

- name: add the user to the group docker
  user: name={{ ansible_ssh_user }} group=docker

- name: start docker engine
  service: name=docker state=running enabled=true

- name: Install docker-py
  package:
    name: python-docker
    state: present

